# SELECT t2.ANIMAL_ID,t2.ANIMAL_TYPE,t2.NAME
# FROM(
#     SELECT *
#     FROM ANIMAL_INS 
#     WHERE SEX_UPON_INTAKE LIKE 'Intact%' 
# ) t1, ANIMAL_OUTS t2
# WHERE t1.ANIMAL_ID = t2.ANIMAL_ID
# AND t2.SEX_UPON_OUTCOME NOT LIKE 'Intact%';

SELECT t2.ANIMAL_ID,t2.ANIMAL_TYPE,t2.NAME
FROM(
    SELECT *
    FROM ANIMAL_INS 
    WHERE SEX_UPON_INTAKE LIKE 'Intact%' 
) t1, ANIMAL_OUTS t2
WHERE t1.ANIMAL_ID = t2.ANIMAL_ID
AND (t2.SEX_UPON_OUTCOME LIKE 'Spayed%' or t2.SEX_UPON_OUTCOME LIKE 'Neutered%');
